/**
 * `devhelp init` — the maintainer growth loop.
 *
 * A maintainer runs this in their repo and gets a working .devhelp.yml for
 * free: devhelp detects the stack (the same detection a real setup uses) and
 * the CI workflows, then writes a recipe pre-filled with the dev/test/build
 * commands it found — plus commented scaffolding for the steps only the
 * maintainer knows (a seed script, a "Postgres must be running" note).
 *
 * Committing that file means every future contributor's `devhelp` run sets the
 * project up out of the box. We also print a README badge and a CONTRIBUTING
 * snippet so adopting it is a copy-paste, not a chore — one maintainer adopting
 * devhelp turns into every contributor discovering it.
 *
 * Deterministic and read-only except for writing the one file (which it refuses
 * to clobber without --force).
 */
import chalk from "chalk";
import boxen from "boxen";
import { promises as fs } from "node:fs";
import * as path from "node:path";
import * as os from "node:os";
import { simpleGit } from "simple-git";
import { detect, isDetectionEmpty, type Detected } from "./detect.js";
import { describe } from "./setup.js";
import { mineCI, fillFromCI } from "./ci-mining.js";
import { repoSlugFromRemote } from "./registry.js";
import { RECIPE_FILENAMES } from "./recipe.js";

export interface InitOptions {
  cwd: string;
  force?: boolean;
  json?: boolean;
}

const DOCS_URL = "https://github.com/sshivanshg/devhelp";

/**
 * Build the .devhelp.yml body from a detection result. Real, detected commands
 * are written live; the steps devhelp can't infer (postInstall, notes) are left
 * as commented examples so the file teaches its own format. Pure + testable.
 */
export function generateRecipeYaml(d: Detected): string {
  const L: string[] = [];
  L.push("# .devhelp.yml — tells devhelp how to set up this repo.");
  L.push("# Generated by `devhelp init`. Edit freely; commit it so contributors");
  L.push("# get a working dev environment in one command.");
  L.push(`# Docs: ${DOCS_URL}#contributing`);
  L.push("");

  if (d.devCommand) {
    L.push("# Command that starts the dev server.");
    L.push(`dev: ${quoteIfNeeded(d.devCommand)}`);
  } else {
    L.push("# dev: <command that starts the dev server>");
  }
  if (d.testCommand) {
    L.push("# Command that runs the test suite.");
    L.push(`test: ${quoteIfNeeded(d.testCommand)}`);
  } else {
    L.push("# test: <command that runs the tests>");
  }
  if (d.buildCommand) {
    L.push("# Command that builds the project.");
    L.push(`build: ${quoteIfNeeded(d.buildCommand)}`);
  } else {
    L.push("# build: <command that builds the project>");
  }

  L.push("");
  L.push("# Extra setup steps no detector can infer — run after install, env,");
  L.push("# and codegen. Uncomment and add yours (e.g. seeding a database):");
  L.push("# postInstall:");
  L.push("#   - make seed");
  L.push("#   - ./scripts/setup.sh");
  L.push("");
  L.push("# Reminders shown to a first-time contributor in the final panel:");
  L.push("# notes:");
  L.push('#   - "Postgres must be running first: docker compose up -d db"');
  L.push("");
  return L.join("\n");
}

/** Quote a YAML scalar only when it could be misread (has a `:` or `#`). */
function quoteIfNeeded(s: string): string {
  return /[:#]/.test(s) ? `"${s.replace(/"/g, '\\"')}"` : s;
}

/** The README badge + the CONTRIBUTING snippet, ready to paste. */
export function adoptionSnippets(slug: string): { badge: string; contributing: string } {
  const cmd = `npx devhelp-cli "set up this project"`;
  const badge = `[![Set up with devhelp](https://img.shields.io/badge/dev%20setup-devhelp-2ea44f)](${DOCS_URL})`;
  const contributing = [
    "## Development setup",
    "",
    `This repo works with [devhelp](${DOCS_URL}) — one command for a working dev environment:`,
    "",
    "```bash",
    slug ? `npx devhelp-cli ${slug}` : cmd,
    "```",
    "",
    "It installs the right runtime, picks the package manager from the lockfile,",
    "copies `.env`, and runs the steps in `.devhelp.yml`.",
  ].join("\n");
  return { badge, contributing };
}

export async function runInit(opts: InitOptions): Promise<number> {
  const detected = await detect(opts.cwd);

  if (isDetectionEmpty(detected)) {
    const msg =
      "devhelp doesn't recognize a stack here, so there's nothing to put in a recipe yet.";
    if (opts.json) {
      console.log(JSON.stringify({ status: "UNSUPPORTED", error: msg }, null, 2));
    } else {
      console.log();
      console.log(chalk.yellow("  " + msg));
      console.log(chalk.dim("  Run it from your project root, or open an issue if the stack should be supported."));
      console.log();
    }
    return 1;
  }

  // Enrich the recipe with build/test commands the repo's CI proves work.
  const ci = await mineCI(opts.cwd);
  if (ci) fillFromCI(detected, ci);

  const slug = await slugFromGit(opts.cwd);
  const yaml = generateRecipeYaml(detected);
  const target = path.join(opts.cwd, RECIPE_FILENAMES[0]);
  const existed = await exists(target);

  if (existed && !opts.force) {
    const msg = `${RECIPE_FILENAMES[0]} already exists — not overwritten. Re-run with --force to replace it.`;
    if (opts.json) {
      console.log(JSON.stringify({ status: "EXISTS", path: target, generated: yaml }, null, 2));
    } else {
      console.log();
      console.log(chalk.yellow("  " + msg));
      console.log();
    }
    return 1;
  }

  await fs.writeFile(target, yaml);

  const { badge, contributing } = adoptionSnippets(slug);

  if (opts.json) {
    console.log(JSON.stringify({ status: "WROTE", path: target, generated: yaml, badge, contributing }, null, 2));
    return 0;
  }

  console.log();
  console.log(
    chalk.green("  ✔"),
    `Wrote ${chalk.bold(prettyPath(target))}`,
    chalk.dim(`(detected: ${describe(detected)})`),
  );
  console.log(chalk.dim("    Review it, fill in any postInstall steps / notes, and commit it."));
  console.log();

  const panel = [
    chalk.bold("Make it discoverable") + chalk.dim(" — paste into your README/CONTRIBUTING:"),
    "",
    chalk.dim("  README badge:"),
    "  " + badge,
    "",
    chalk.dim("  CONTRIBUTING.md section:"),
    ...contributing.split("\n").map((l) => "  " + chalk.cyan(l)),
  ].join("\n");
  console.log(
    boxen(panel, {
      padding: { top: 1, bottom: 1, left: 2, right: 2 },
      borderStyle: "round",
      borderColor: "green",
      title: chalk.bold("devhelp init"),
      titleAlignment: "center",
    }),
  );
  console.log();
  return 0;
}

async function slugFromGit(dir: string): Promise<string> {
  try {
    const url = await simpleGit({ baseDir: dir }).remote(["get-url", "origin"]);
    const slug = url ? repoSlugFromRemote(url.trim()) : null;
    return slug ? `${slug.owner}/${slug.repo}` : "";
  } catch {
    return "";
  }
}

async function exists(p: string): Promise<boolean> {
  try {
    await fs.access(p);
    return true;
  } catch {
    return false;
  }
}

function prettyPath(p: string): string {
  return p.replace(os.homedir(), "~");
}
